[[hooks]]
subject = "echo"
workdir = "/"
command = "cat"

[[hooks]]
subject = "count"
workdir = "/"
command = "wc -c"

[[hooks]]
subject = "inline"
inline = """
content=$(cat)
echo "== echo =="
echo -E "${content}"
echo "== count =="
echo -E "${content}" | wc -c
"""
